name: matrix
on: [push]
jobs:
  echo:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            binary: dgs-codegen
            os-name: linux
          - os: macos-latest
            binary: dgs-codegen
            os-name: macos
          - os: windows-latest
            binary: dgs-codegen.exe
            os-name: windows
    steps:
      - run: echo ${{ matrix.os }}-${{ matrix.binary }}-${{ matrix.os-name }}-${{ github.ref }}
        id: echo
      - run: echo ${{ steps.echo.outputs }}
