name: matrix
on: [push]
jobs:
  echo:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            binary: dgs-codegen
            os-name: linux
          - os: macos-latest
            binary: dgs-codegen
            os-name: macos
          - os: windows-latest
            binary: dgs-codegen.exe
            os-name: windows
    steps:
      - run: echo ${{ matrix.os }}-${{ matrix.binary }}-${{ matrix.os-name }}-${{ github.ref }}
        id: echo
      - run: mkdir -p foo/bar && echo hello > foo/bar/baz
      - uses: actions/upload-artifact@v2
        with:
          name: binary-${{ matrix.os-name }}
          path: ./foo/bar/*
  download:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: binary-${{ matrix.os-name }}
      - run: ls
      - run: ls foo
      - run: ls foo/bar
