name: release-hook
on:
  release:
    types: published
jobs:
  echo:
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.event.release.url }}
      - run: echo ${{ github.event.release.upload_url }}
